### ISSUE TITLE
I: ICD loader reports no usable platforms

### ISSUE THREAD

**Issue by ghost** [vchuravy/qjulia_gpu#3]
Hi Guys,

I am a beginner in using linux and need to get information from "clinfo" command that should show me details of your gpu (& cpu), but instead I get "I: ICD loader reports no usable platforms" this sentence. 

Is there anyone here that can help me fix this issue? Thanks.

Cheers,
Ladan

**Comment by SimonDanisch** [comment]
Did you install the OpenCL drivers!?

**Comment by ghost** [comment]
Hi Simon, I uninstalled and installed AMD drivers but not sure the OpenCL driver is different?

**Comment by SimonDanisch** [comment]
AMD drivers as in [AMD OpenCL](http://support.amd.com/en-us/kb-articles/Pages/OpenCL2-Driver.aspx) drivers!?

**Comment by ghost** [comment]
yes, I think so not sure how to check this, but I installed it from the same page you sent

**Comment by SimonDanisch** [comment]
Hm... I'm not really the pro in installing OpenCL myself. Sorry, someone else or google has to help you here!

**Comment by ghost** [comment]
Thanks Simon

**Comment by vchuravy** [comment]
@ladanks Which Linux distribution are you using? Installing OpenCL is different for each of them

**Comment by ghost** [comment]
Ubuntu Desktop 14.04, 64 bit

**Comment by vchuravy** [comment]
If you are installing fglrx/catalyst OpenCL should be automatically installed

**Comment by ghost** [comment]
When trying to install fglrx-updates, I get the following error:

Preparing to unpack .../fglrx-updates-core_2%3a15.200-0ubuntu0.3_amd64.deb ...
Unpacking fglrx-updates-core (2:15.200-0ubuntu0.3) ...
dpkg: error processing archive /var/cache/apt/archives/fglrx-updates-core_2%3a15.200-0ubuntu0.3_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/clinfo', which is also in package clinfo 0.0.20130513-1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/fglrx-updates-core_2%3a15.200-0ubuntu0.3_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by vchuravy** [comment]
`sudo apt-get remove clinfo && sudo apt-get install fglrx-updates`

should do the trick. But since I am not running Ubuntu I can make sure.

**Comment by ghost** [comment]
Thank you so much for the prompt feedback! fglrx installation seems to work. I, however, get the following when I run clinfo:
~$ clinfo
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Aborted (core dumped)

**Comment by ghost** [comment]
Also, 
~$ fglrxinfo
Error: unable to open display (null)

**Comment by vchuravy** [comment]
That seems to be this:
http://askubuntu.com/questions/632045/opencl-only-works-as-root

**Comment by ghost** [comment]
Thank you so much. It works.

**Comment by ghost** [comment]
Vchuravy I thoought the problem has been solved and then I get this error:

ladan@Linux-workstation:~$ clinfo
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Aborted (core dumped)

**Comment by vchuravy** [comment]
Sorry, I don't think I can help you any further. I don't have much
experience with Ubuntu and OpenCL, best thing would be to post to their
user forums
